#!/usr/bin/env node

var program = require("commander");
var fs = require("fs");

program.parse(process.argv);

var portal = program.args[0];
if (!portal) {
    console.error("error: specify a portal to unfollow");
    return;
}

return new Promise((resolve, reject) => {
    fs.readFile(".rotonde", (err, data) => {
        if (err) { reject(err); }
        resolve(JSON.parse(data));
    })
}).then((settings) => {
    return new Promise((resolve, reject) => {
        fs.readFile(settings["rotonde location"], (err, data) => {
            if (err) { reject(err) };
            resolve([JSON.parse(data), settings]); // parse rotonde info & pass along settings
        });
    });
}).then((rotondeItems) => {
    var [rotonde, settings] = rotondeItems;
    var index = rotonde["portal"].indexOf(portal);
    if (index < 0) {
        console.log("err: you aren't following", portal);
        return;
    }
    rotonde["portal"].splice(rotonde["portal"].indexOf(portal), 1); // remove portal we want to unfollow
    fs.writeFile(settings["rotonde location"], JSON.stringify(rotonde), function(err) {
        if (err) { 
            console.error("err: couldn't save to", settings["rotonde location"]);
            console.error(err);
            return;
        }
        console.log("no longer following", portal);
    })
})

