#!/usr/bin/env node

var program = require("commander");
var fs = require("fs");

program.parse(process.argv);

var color = program.args[0];
if (!color) {
    console.error("error: the color to write on your profile");
    return;
}

return new Promise((resolve, reject) => {
    fs.readFile(".rotonde", (err, data) => {
        if (err) { reject(err); }
        resolve(JSON.parse(data));
    })
}).then((settings) => {
    return new Promise((resolve, reject) => {
        fs.readFile(settings["rotonde location"], (err, data) => {
            if (err) { reject(err) };
            resolve([JSON.parse(data), settings]); // parse rotonde info & pass along settings
        });
    });
}).then((rotondeItems) => {
    var [rotonde, settings] = rotondeItems;
    rotonde["profile"]["color"] = color;
    fs.writeFile(settings["rotonde location"], JSON.stringify(rotonde), function(err) {
        if (err) { 
            console.error("err: couldn't save to", settings["rotonde location"]);
            console.error(err);
            return;
        }
        console.log("your color was changed to", color);
    })
})

