#!/usr/bin/env node

var program = require("commander");
var fs = require("fs");

program.parse(process.argv);

var portal = program.args[0];
if (!portal) {
    console.error("error: specify a portal to follow");
    return;
}

console.log(portal);
return new Promise((resolve, reject) => {
    fs.readFile(".rotonde", (err, data) => {
        if (err) { reject(err); }
        resolve(JSON.parse(data));
    })
}).then((settings) => {
    return new Promise((resolve, reject) => {
        fs.readFile(settings["rotonde location"], (err, data) => {
            if (err) { reject(err) };
            resolve([JSON.parse(data), settings]); // parse rotonde info & pass along settings
        });
    });
}).then((rotondeItems) => {
    var [rotonde, settings] = rotondeItems;
    rotonde["portal"].push(portal); // save the portal we want to follow
    fs.writeFile(settings["rotonde location"], JSON.stringify(rotonde), function(err) {
        if (err) { 
            console.error("err: couldn't save portal to rotonde.json");
            console.error(err);
            return;
        }
        console.log("saved", portal);
    })
})

