#!/usr/bin/env node

var program = require("commander");
var fs = require("fs");
var crypto = require("crypto");

program.parse(process.argv);

var index = program.args
if (!index.length) {
    console.error("error: specify an entry to post to your feed");
    return;
}

return new Promise((resolve, reject) => {
    fs.readFile(".rotonde", (err, data) => {
        if (err) { reject(err); }
        resolve(JSON.parse(data));
    })
}).then((settings) => {
    return new Promise((resolve, reject) => {
        fs.readFile(settings["rotonde location"], (err, data) => {
            if (err) { reject(err) };
            resolve([JSON.parse(data), settings]); // parse rotonde info & pass along settings
        });
    });
}).then((rotondeItems) => {
    var [rotonde, settings] = rotondeItems;
    index.forEach((i) => {
        rotonde["feed"].splice(i, 1);
    });
    fs.writeFile(settings["rotonde location"], JSON.stringify(rotonde), function(err) {
        if (err) { 
            console.error("err: couldn't save to", settings["rotonde location"]);
            console.error(err);
            return;
        }
        console.log("following entries were deleted:", index);
    })
})

