#!/usr/bin/env node

var program = require("commander");

program
  .version("0.0.1")
  .command("follow [rotonde domain]", "follow a rotonde domain").alias("f")
  .command("unfollow [name]", "unfollow a rotonde domain").alias("u")
  .command("name [name]", "set your profile name").alias("n")
  .command("location [name]", "set your profile location").alias("l")
  .command("color [name]", "set your profile color").alias("c")
  .command("write [entry]", "write an entry").alias("w")
  .command("feed", "view your feed").alias("f")
  .command("visit [portal]", "visit a rotonde portal").alias("v")
  .command("save", "save the location of your rotonde.json file").alias("p")
  .parse(process.argv);

// here .command() is invoked with a description,
// and no .action(callback) calls to handle sub-commands.
// this tells commander that you"re going to use separate
// executables for sub-commands, much like git(1) and other
// popular tools.

// here only ./pm-install(1) is implemented, however you
// would define ./pm-search(1) and ./pm-list(1) etc.

// Try the following:
//   ./examples/pm
//   ./examples/pm help install
//   ./examples/pm install -h
//   ./examples/pm install foo bar baz
//   ./examples/pm install foo bar baz --force
