#!/usr/bin/env node

var program = require("commander");
var fs = require("fs");

program.parse(process.argv);

var portal = program.args[0];
if (!portal) {
    console.error("error: specify a portal to follow");
    return;
}

console.log(portal);

return new Promise((resolve, reject) => {
    fs.readFile(".rotonde", (err, data) => {
        if (err) { reject(err); }
        resolve(data);
    })
}).then((rotondePath) => {
    console.log(rotondePath);
});
// var rotondeFile = path.resolve(portal, "rotonde.json")
//
// console.log("saving the portal of your rotonde file as", portal + "...");
//
// return new Promise(function(resolve, reject) {
//     fs.writeFile(".rotonde", {"rotonde portal": portal}, function(err) {
//         if (err) {
//             console.error("failed to create settings file at", portal);
//         }
//         console.log("portal remembered!");
//         resolve();
//     });
// })
// .then(function() {
//     fs.stat(rotondeFile, function(err, stat) {
//         if (err == null) {
//             // file already exists
//         } else if (err.code == "ENOENT") {
//             console.log("no rotonde.json at that portal, creating one with the base structure...")
//             fs.writeFile(rotondeFile, JSON.stringify(rotondeStructure), function(err) {
//                 if (err) {
//                     console.log(err);
//                     console.error("failed to create rotonde.json file at", portal);
//                     return;
//                 }
//                 console.log("rotonde.json created!");
//             });
//         } else {
//             console.log("err", err.code);
//         }
//     });
// });
